# Blob Input tests

@baseUrl = http://localhost:7071/api
@id = ea225e8c-945e-47ae-9560-9bcdf5077c58
### Stream
GET {{baseUrl}}/GetPlayerWithStreamInput/{{id}}

### Dynamic
GET {{baseUrl}}/GetPlayerWithStringInputDynamic?id={{id}}

### BlobList
GET {{baseUrl}}/GetBlobNamesWithBlobContainerInput