# Blob output requests

@baseUrl = http://localhost:7071/api
### String
POST {{baseUrl}}/StorePlayerWithStringBlobOutput
Content-Type: application/json

{
    "id": "{{$guid}}",
    "nickName" : "Ada",
    "email" : "ada@lovelace.org",
    "region" : "United Kingdom"
}

### Stream
POST {{baseUrl}}/StorePlayerWithStreamBlobOutput
Content-Type: application/json

{
    "id": "{{$guid}}",
    "nickName" : "Grace",
    "email" : "grace@hopper.org",
    "region" : "United States of America"
}

### Dynamic Binding
POST {{baseUrl}}/StorePlayerWithStringBlobOutputDynamic
Content-Type: application/json

{
    "id": "{{$guid}}",
    "nickName" : "Margaret",
    "email" : "margaret@hamilton.org",
    "region" : "United States of America"
}

### CloudBlockBlob
POST {{baseUrl}}/StorePlayerWithContainerBlobOutput
Content-Type: application/json

{
    "id": "{{$guid}}",
    "nickName" : "Margaret",
    "email" : "margaret@hamilton.org",
    "region" : "United States of America"
}