# Blob input requests

@baseUrl = http://localhost:7071/api
@id = 470ef8af-27f9-469f-95a2-48b027e0ffff

### Stream
GET {{baseUrl}}/GetPlayerWithStreamInput/{{id}}

### Dynamic
GET {{baseUrl}}/GetPlayerWithStringInputDynamic?id={{id}}

### BlobList
GET {{baseUrl}}/GetBlobNamesWithContainerBlobInput