name: '.NET 6 builds'
on:
  pull_request:
      types: [opened, edited, synchronize, reopened]
      paths:
        - 'src/dotnet6/**'
        - '.github/workflows/dotnet6.yml'
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  Application:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
    - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: 'Build HTTP Function'
      shell: bash
      run: |
        pushd './src/dotnet6/http/AzFuncUni.Http'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Build HTTP Refit Function'
      shell: bash
      run: |
        pushd './src/dotnet6/http-refit/AzFuncUni.Http'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Build Advanced Scenarios using Refit'
      shell: bash
      run: |
        pushd './src/dotnet6/http-refit-auth/AzFuncUni.Http'
        dotnet build --configuration Release --output ./output
        popd